name: Build and deploy JAR app to Azure Web App - creadev-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Gradle (skip tests)
        run: ./gradlew clean bootJar -x test

      - name: Copy JAR to root for deployment
        run: |
          mkdir package
          cp build/libs/app.jar package/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DA84EB117C7646EEB1E873B2F9A9BD7F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_760AD7E83C2842C59DA7B15542368B3D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9CB722C5298A49DD8816E05C35EFDD57 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'creadev-api'
          slot-name: 'Production'
          package: 'app.jar'