name: Build and deploy GraalVM native image to Azure Web App - creadev-api

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - '.github/workflows/main_creadev-api.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up GraalVM for Java 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native image
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DRIVER: ${{ secrets.DB_DRIVER }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
          JWT_ACCESS_VALIDITY: ${{ secrets.JWT_ACCESS_VALIDITY }}
          JWT_REFRESH_VALIDITY: ${{ secrets.JWT_REFRESH_VALIDITY }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_FIRST_NAME: ${{ secrets.ADMIN_FIRST_NAME }}
          ADMIN_LAST_NAME: ${{ secrets.ADMIN_LAST_NAME }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PHONE: ${{ secrets.ADMIN_PHONE }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./gradlew nativeCompile -x test

      - name: Copy native binary to package folder
        run: |
          mkdir package
          cp build/native/nativeCompile/app package/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-app
          path: package/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: native-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DA84EB117C7646EEB1E873B2F9A9BD7F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_760AD7E83C2842C59DA7B15542368B3D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9CB722C5298A49DD8816E05C35EFDD57 }}

      - name: Deploy native binary to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'creadev-api'
          slot-name: 'Production'
          package: '.'